runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /assets/
  static_dir: templates/assets/


- url: /.*/assets/
  static_dir: templates/assets/

- url: /.*
  script: app.app

libraries:
- name: flask
  version: latest

- name: ssl
  version: latest
